# Use an official Node.js runtime as a parent image
FROM node:lts-alpine

# Set the working directory in the container
WORKDIR '/app'

# Install dependencies
COPY package.json .
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the app runs on
CMD ["npm", "run", "start"]